name: Publish Bandersnatch to Docker on Release "$GITHUB_REF"
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry "$GITHUB_REF"
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: pypa/bandersnatch
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}